In [2]:
import geopandas as gpd
import os

input_file = 'test-data/HGC-borders-19380430-v1.gpkg'
core_file_name = os.path.splitext(os.path.basename(input_file))[0]
print(core_file_name)

HGC-borders-19380430-v1

In [36]:
dataset = gpd.read_file(input_file)
dataset.head()

,Name,Foreign_Po,Head_of_St,Govt_in_Ex,Shape_Leng,Shape_Area,geometry
0,Greece,<Null>,General Ioannis Metaxas,None,1.376915e+07,1.296478e+11,"MULTIPOLYGON (((2227508.963 4820987.876, 22281..."
1,Netherlands,<Null>,Queen Wihelmina,None,2.720118e+06,3.546712e+10,"MULTIPOLYGON (((460323.793 6685502.625, 460649..."
2,Belgium,<Null>,King Léopold III,None,1.368014e+06,3.068437e+10,"MULTIPOLYGON (((549421.337 6693177.780, 548559..."
3,France,<Null>,Édouard Daladier (Prime Minister),None,8.295515e+06,5.494437e+11,"MULTIPOLYGON (((1030574.342 5063188.952, 10304..."
4,Spain,<Null>,Manuel Azaña Díaz (President),None,8.117024e+06,5.060875e+11,"MULTIPOLYGON (((-1537354.526 3346278.804, -153..."

In [37]:
for i in range(len(dataset)):
    print(i)
    new_layer_name = core_file_name + "-" + str(i)
    newgdf = dataset.filter(items=[i], axis=0)
    newgdf.info()
    newgdf.to_file(input_file, layer=new_layer_name, driver="GPKG")

0
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
1
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 1 to 1
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
2
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 2 to 2
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
3
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 3 to 3
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
4
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 4 to 4
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
5
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 5 to 5
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
6
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 6 to 6
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
7
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 7 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
8
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 8 to 8
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
9
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 9 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
10
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 10 to 10
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
11
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 11 to 11
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
12
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 12 to 12
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  0 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
13
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 13 to 13
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
14
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 14 to 14
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
15
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 15 to 15
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
16

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 16 to 16
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
17
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 17 to 17
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  0 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
18
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 18 to 18
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  0 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
19
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 19 to 19
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
20
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 20 to 20
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
21
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 21 to 21
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  0 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
22
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 22 to 22
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  0 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
23
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 23 to 23
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  0 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
24
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 24 to 24
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  0 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
25
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 25 to 25
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  0 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
26
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 26 to 26
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
27
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 27 to 27
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
28
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 28 to 28
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
29
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 29 to 29
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
30
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 30 to 30
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
31
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 31 to 31
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
32
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 32 to 32
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes

33
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 33 to 33
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
34
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 34 to 34
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  0 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
35
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 35 to 35
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
36
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 36 to 36
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes
37
<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 1 entries, 37 to 37
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        1 non-null      object
 1   Foreign_Po  1 non-null      object
 2   Head_of_St  1 non-null      object
 3   Govt_in_Ex  0 non-null      object
 4   Shape_Leng  1 non-null      float64
 5   Shape_Area  1 non-null      float64
 6   geometry    1 non-null      geometry
dtypes: float64(2), geometry(1), object(4)
memory usage: 64.0+ bytes

In [38]:
import fiona

In [39]:
for layername in fiona.listlayers(input_file):
    with fiona.open(input_file, layer=layername) as src:
        print(layername, len(src))

HGC-borders-19380430-v1 38
HGC-borders-19380430-v1-0 1
HGC-borders-19380430-v1-1 1
HGC-borders-19380430-v1-2 1
HGC-borders-19380430-v1-3 1
HGC-borders-19380430-v1-4 1
HGC-borders-19380430-v1-5 1
HGC-borders-19380430-v1-6 1
HGC-borders-19380430-v1-7 1
HGC-borders-19380430-v1-8 1
HGC-borders-19380430-v1-9 1
HGC-borders-19380430-v1-10 1
HGC-borders-19380430-v1-11 1
HGC-borders-19380430-v1-12 1
HGC-borders-19380430-v1-13 1
HGC-borders-19380430-v1-14 1
HGC-borders-19380430-v1-15 1
HGC-borders-19380430-v1-16 1
HGC-borders-19380430-v1-17 1
HGC-borders-19380430-v1-18 1
HGC-borders-19380430-v1-19 1
HGC-borders-19380430-v1-20 1
HGC-borders-19380430-v1-21 1
HGC-borders-19380430-v1-22 1
HGC-borders-19380430-v1-23 1
HGC-borders-19380430-v1-24 1
HGC-borders-19380430-v1-25 1
HGC-borders-19380430-v1-26 1
HGC-borders-19380430-v1-27 1
HGC-borders-19380430-v1-28 1
HGC-borders-19380430-v1-29 1
HGC-borders-19380430-v1-30 1
HGC-borders-19380430-v1-31 1
HGC-borders-19380430-v1-32 1
HGC-borders-19380430-v1-33 1
HGC-borders-19380430-v1-34 1
HGC-borders-19380430-v1-35 1
HGC-borders-19380430-v1-36 1
HGC-borders-19380430-v1-37 1

In [40]:
l = gpd.read_file(input_file, layer='HGC-borders-19380430-v1-1')
l

,Name,Foreign_Po,Head_of_St,Govt_in_Ex,Shape_Leng,Shape_Area,geometry
0,Netherlands,<Null>,Queen Wihelmina,None,2.720118e+06,3.546712e+10,"MULTIPOLYGON (((460323.793 6685502.625, 460649..."

In [34]:
# get bounding box
l.bounds

            minx          miny           maxx          maxy
0  373779.828872  6.577263e+06  804419.282665  7.087222e+06